spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url-shortener-interns
    username: postgres
    password: password123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.sorsix.urlshortenerinterns: debug
